pipeline {
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'

        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd spring-boot-app && mvn clean package'
            }
        }
        stage('sonar qube ') {
            environment {
                SONARQUBE_URL= "http://localhost:9000"   
            }
            steps {
                withCredentials([string(CredentialsID:'jenkins',Variables:'SONARQUBE_AUTH_TOKEN')]) {
                sh 'cd spring-boot-java/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONARQUBE_AUTH_TOKEN -Dsonar.host.url=$SONARQUBE_URL'
              }
           }
        }
    }
}
